### PR TITLE
Created a folder src to parallel test

### PR DESCRIPTION
**Pull request by dcstone09**
I moved the source code to a source directory, the files parallel those in the test directory. This commit triggered the linter and formatted the code.

### CODE REVIEW

**Comment by ZacharyDavidSaunders** [comment]
Thank you. Would this need to be updated too?
https://github.com/dcstone09/PseudonameAPI/blob/4a36d4f35bb4a691c550bff8d23857ebd8b75b7c/package.json#L8

**Comment by dcstone09** [comment]
Good Catch! I updated the package.json

**Comment by ZacharyDavidSaunders** [comment]
Sorry for the delay on this. Now merged, but the tests are failing. I'm going to look into it.
CI Build: https://travis-ci.com/ZacharyDavidSaunders/PseudonameAPI/builds/106251209

**Comment by ZacharyDavidSaunders** [comment]
I see the issue. The ForwardMX API is taking too long to respond (probably because it's encumbered by a ton of fake data). I'll purge some data and try again.

**Comment by ZacharyDavidSaunders** [comment]
Data purged, build restarted and passed, code deployed. This is all wrapped up now.

**Pull request merged**
