### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by dcstone09**
This is a few recommended update for a node API. I'm opening the pull request as a draft for early feedback on the changes.

### CODE REVIEW

**Comment by mvpowers** [comment]
@dcstone09
I think this looks great. Hot fire. 🔥 🚀 💯 

@ZacharyDavidSaunders 
Here is a link to an issue regarding inconsistent extrusion. 
https://github.com/prusa3d/Prusa-Firmware/issues/602

**Comment by ZacharyDavidSaunders** [comment]
I really like this @dcstone09, thanks. I'm preparing to rebuild the API to make it more standard and secure and this is a great addition. I'd like to roll out all the changes at once, in one large update, so here's what I suggest, let's leave this here until the other pieces are in place and then add this at the end. I might ask you to merge this into a different branch when that time comes. Thanks again!

@mvpowers Are you getting into the 3D printing space?

**Comment by dcstone09** [comment]
@ZacharyDavidSaunders cool, I have a few other things for this, we can set a project in github and make some tickets / goals.

**Comment by ZacharyDavidSaunders** [comment]
Sounds good. I've made a project that we can start using (https://github.com/ZacharyDavidSaunders/PseudonameAPI/projects/1). I'm not sure what kind of project/issue interaction access you have. Let me know if you need any permissions. I can make you a collaborator if needed.

**Comment by ZacharyDavidSaunders** [comment]
@dcstone09 I've only got one issue left on the project board and I'll wrap it up in the next day or two. Now would be a great time for you to list out the tickets that you wanted to create. If you're busy, that's not a problem, I can release what I have and include your changes in a later release. Just let me know.

@mvpowers Are you looking to get involved too?

**Comment by dcstone09** [comment]
@ZacharyDavidSaunders Go for an earlier release if you can, I have several recommendations still. We can address them soon though.

**Comment by mvpowers** [comment]
@ZacharyDavidSaunders I am here for all morale support needs.

**Pull request closed without merging**
