### PR TITLE
Added Eslint and a Prettier for code formatting on git commit.

### PR DESCRIPTION
**Pull request by dcstone09**
Nice API here! This PR set's up automatic formatting. I set it to Airbnb but it can be configured any way the project needs. Right now it will only format files staged in git on commit.

### CODE REVIEW

**Comment by dcstone09** [comment]
I'm not sure why the build fails, I can check it out later but I don't think it's related to this commit.

**Comment by mvpowers** [comment]
MOVE FAST AND BREAK THINKS
LGTM! 🚀

**Comment by ZacharyDavidSaunders** [comment]
Hey guys, thanks for checking this out and submitting a PR! 😄 

I looked into why the build is failing. After looking at the logs, I've discovered that the API requests are missing the ForwardMX API key, which is causing a 500 response.

For some reason, with this commit, the requests are no longer accessing the key, which is stored as an environment variable in Travis.

 Here's an example:
```https://forwardmx.io/api/alias/create?&key=undefined&domain=pseudoname.io&destination=test@gmail.com&alias=newAlias```, you can see that `key=undefined`. 

I double checked that the key is in Travis, I even re-added it just to be safe. I also restarted the [previous build (Build 16)](https://travis-ci.com/ZacharyDavidSaunders/PseudonameAPI/builds/101488972) and it was successful (which means that it was able to get the key). This leads me to believe that maybe adding a new dependency threw the system off. I'm going to look into whether I need to tell travis to run `npm install` before the running the tests.

**Comment by dcstone09** [comment]
@ZacharyDavidSaunders Thanks for checking it out, I'll look into it later aswell. Maybe the service could be mocked out of the test suite?

**Comment by ZacharyDavidSaunders** [comment]
Yeah, I can run it locally, just have to save the API key as a environment variable on my machine. I'll give this a try in a little bit.

**Comment by ZacharyDavidSaunders** [comment]
Okay, so I downloaded your changes and ran `npm test` against them locally and everything passed. So this seems like a problem with Travis CI. I'm going to open a ticket with them and see if they know what's wrong.

**Comment by dcstone09** [comment]
@ZacharyDavidSaunders No need to open a ticket with TravisCI, your ENV variables are not set or not being read properly. The test is sending requests with a query parameter of "key=undefined" so please make sure Travis CI has "herokuForwardMXApiKey" or "localForwardMxApiKey" set.

**Comment by ZacharyDavidSaunders** [comment]
Yes, I'm sure it's set, here's a screenshot:
screen shot 2019-02-19 at 12 45 20 pm

**Comment by moaxaca** [comment]
Travis isn't happy with you

**Comment by ZacharyDavidSaunders** [comment]
My local tests read that same key and work fine, and Travis _did_ work with that key in the build before this change. Your change has nothing to do with the key so I'm fairly certain that Travis is at fault here.

**Comment by dcstone09** [comment]
@ZacharyDavidSaunders I think this might be the root cause https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions

**Comment by ZacharyDavidSaunders** [comment]
I decided to just merge it and work out the TravisCI stuff later. Regardless, thanks for the linter @dcstone09!

**Pull request merged**
